ALTER TABLE public.files
  ADD COLUMN IF NOT EXISTS sha256 TEXT,
  ADD COLUMN IF NOT EXISTS vt_stats JSONB,
  ADD COLUMN IF NOT EXISTS vt_scanned_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS files_sha256_idx ON public.files(sha256);